#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "-->oooooooo ACTION HOOK ooooooooooooo: build <--"

if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
mkdir $OPENSHIFT_DATA_DIR/media
fi

ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/media

OLD_HOME=$HOME
export HOME=$OPENSHIFT_REPO_DIR
if [ -f "${OPENSHIFT_REPO_DIR}"/Gulpfile.js ]; then
 (cd "${OPENSHIFT_REPO_DIR}"; $OPENSHIFT_HOME_DIR/app-root/dependencies/node_modules/.bin/gulp)
fi
export HOME=$OLD_HOME
