#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "--> ACTION HOOK: pre_build <--"
cd $DEPENDENCY_BASE; wget https://nodejs.org/dist/v4.4.7/node-v4.4.7-linux-x64.tar.xz; tar -xf node-v4.4.7-linux-x64.tar.xz; mv node-v4.4.7-linux-x64 node; rm node-v4.4.7-linux-x64.tar.xz; rm -rf node-v4.4.7-linux-x64
mkdir -p $DEPENDENCY_BASE/.npm $DEPENDENCY_BASE/node_modules/.bin
export PATH="$DEPENDENCY_BASE/node_modules/.bin/:$DEPENDENCY_BASE/node/bin/:$PATH"
export NPM_CONFIG_USERCONFIG=$OPENSHIFT_HOMEDIR/app-root/build-dependencies/.npmrc
node --version; npm --version
npm config set cache "$DEPENDENCY_BASE/.npm"
cd $OPENSHIFT_REPO_DIR
npm install gulp gulp-cssnano gulp-autoprefixer gulp-sass gulp-uglify
./node_modules/.bin/gulp --gulpfile ./gulpfile.js
