#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "--> ACTION HOOK: pre_build <--"
export PATH="$DEPENDENCY_BASE/node_modules/.bin/:$DEPENDENCY_BASE/node/bin/:$PATH"
export NPM_CONFIG_USERCONFIG=$OPENSHIFT_HOMEDIR/app-root/build-dependencies/.npmrc
node --version; npm --version
npm config set cache "$DEPENDENCY_BASE/.npm"
cd $OPENSHIFT_REPO_DIR
npm install gulp
gulp --gulpfile $OPENSHIFT_REPO_DIR/gulpfile-openshift.js
